version: '3.8'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiwikrama
      POSTGRES_DB: wcn
    networks:
      - wcn
networks:
  wcn:

